### PR TITLE
Support import type. Fixes #10

### LINKED ISSUE #10: Preserve /*@flow*/ and import type statements
Currently, even with the plugin, `/* @flow */` is stripped, so I can't use this as is for publishing a Flow-enabled module on NPM.

Another issue is that `import type` does not seem to be preserved. It needs to be wrapped into `/*:: */` in order for the references to make sense.

#### Source

```js
/* @flow */

import type { Stuff } from './types';

function lol(x: Stuff) {
}
```

#### Actual output

```js
'use strict';

function lol(x /*: Stuff*/) {}
```

#### Expected output

```js
/* @flow */

'use strict';

/*::
  import type { Stuff } from './types';
*/

function lol(x /*: Stuff*/) {}
```

### PR DESCRIPTION
**Pull request by gaearon**
Sorry if not very idiomatic.
My first time contributing to a Babel plugin.

### CODE REVIEW

**Comment by sebmck** [comment]
Actually, I should probably fix this in core by making the `Flow` virtual type return `true` for the special imports.

**Comment by gaearon** [comment]
Should we delay merging? I'm happy to amend the code later to depend on Babel core fixes, but I'd rather get the correct behavior faster. (I'm happy to use my fork in the time being though.)

**Comment by sebmck** [comment]
I'm fine with a temporary fix, this may conflict with other PRs so I'll delegate to @hzoo on this.

**Comment by hzoo** [comment]
Since #13 needs to wait on a change in flow itself we can merge this first as temp fix and I'l change #13 to match

**Comment by hzoo** [comment]
@gaearon Maybe create an issue in core as a reminder?

**Comment by hzoo** [comment]
Ok published `1.0.5` with this!

**Comment by gaearon** [comment]
Thank you!

**Pull request merged**
